apiVersion: batch/v1
kind: Job
metadata:
  name: odh-manifests-test-job
  namespace: redhat-ods-applications
  labels:
    app:  odh-manifests-test-job
    test: osd-e2e-test
spec:
  backoffLimit: 2
  completions: 1
  template:
    metadata:
      name: odh-manifests-test-pod
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - $HOME/peak/installandtest.sh
        env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TESTS_REGEX
          value: jupyterhub_load
        - name: ODHPROJECT
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ARTIFACT_DIR
          value: /tmp/artifacts
        # - name: SKIP_INSTALL
        #   value: "TRUE"
        - name: SKIP_OPERATOR_INSTALL
          value: "TRUE"
        - name: SKIP_KFDEF_INSTALL     
          value: "TRUE"
        # - name: JH_NOTEBOOK_SIZE      # Set Medium size, if you want to create a bigger jupyter notebook 
        #   value: "Medium"        
        - name: PUSHGATEWAY_URL
          value: "CHANGE_ME"      
        image: quay.io/modh/odh-manifests-test:latest
        name: odh-manifests-test
        resources: {}
        volumeMounts:
        - mountPath: /tmp/artifacts
          name: artifacts
      volumes:
      - emptyDir: {}
        name: artifacts
      restartPolicy: Never
      serviceAccountName: odh-manifests-test-sa



